addons:
  apt:
    packages:
      - openjdk-6-jdk
      - openjdk-9-jdk
      - oracle-java9-installer
language: java
jdk:
    - openjdk6
    - openjdk7
    - openjdk8
    - openjdk9
    - oraclejdk8
    - oraclejdk9
notifications:
    email: false
sudo: false
